title: Valtteri Kurkela # your name (or website title) here
logo: "/images/new_selfie.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <a href="https://kurval.github.io/online-cv/" target="_blank"">View My Resume</a> 
  <br>
  <a href="https://github.com/kurval">
    <img src="https://cdn.jsdelivr.net/gh/dmhendricks/signature-social-icons/icons/round-flat-filled/50px/github.png" alt="Github" title="Github" width="25" height="25" />
  </a>
  <a href="https://www.linkedin.com/in/valtterikurkela/">
    <img src="https://cdn.jsdelivr.net/gh/dmhendricks/signature-social-icons/icons/round-flat-filled/50px/linkedin.png" alt="Linkedin" title="Linkedin" width="25" height="25" />
  </a>
  <a href="https://twitter.com/KurkelaValtteri">
    <img src="https://cdn.jsdelivr.net/gh/dmhendricks/signature-social-icons/icons/round-flat-filled/50px/twitter.png" alt="Twitter" title="Twitter" width="25" height="25" />
  </a>
logo2: "/images/skills.png?raw=true" # additional photo
theme: jekyll-theme-minimal
google_analytics: UA-168211411-1 # your Google Analytics tracking ID here
