title: Valtteri Kurkela # your name (or website title) here
logo: "/images/new_selfie.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Skills
  logo2: "/images/skills.png?raw=true" # additional photo
  <br><br>
  <a href="https://www.linkedin.com/in/valtterikurkela/">View My LinkedIn Profile</a> 
  <br>
  <a <img src="/images/skills.png" width="100" height="100" /></a>
theme: jekyll-theme-minimal
google_analytics: UA-168211411-1 # your Google Analytics tracking ID here

