title: Valtteri Kurkela # your name (or website title) here
logo: "/images/new_selfie.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Programming student and experienced consultant who has proven experience in working on fast paced software development projects. Supportive team player with good technical and social skills. Worked in the financial services in different roles such as business analyst, technical product owner, software tester.
  <br>
  <a href="https://www.linkedin.com/in/valtterikurkela/">View My LinkedIn Profile</a> 
logo2: "/images/skills.png?raw=true" # additional photo
theme: jekyll-theme-minimal
google_analytics: UA-168211411-1 # your Google Analytics tracking ID here

