title: Valtteri Kurkela # your name (or website title) here
logo: "/images/new_selfie.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <a href="https://kurval.github.io/online-cv/" target="_blank"">View My Resume</a> 
  <br>
  <a href="https://github.com/kurval">
    <img align="left" width="25px" src="https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/github.svg" />
  </a>
  <a href="https://www.linkedin.com/in/valtterikurkela/">
    <img align="left" width="25px" src="https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/linkedin.svg" />
  </a>
  <a href="https://twitter.com/KurkelaValtteri">
    <img align="left" width="25px" src="https://cdn.jsdelivr.net/npm/simple-icons@v3/icons/twitter.svg" />
  </a>
logo2: "/images/skills.png?raw=true" # additional photo
theme: jekyll-theme-minimal
google_analytics: UA-168211411-1 # your Google Analytics tracking ID here
